### ISSUE TITLE
https not supported in download_file

### ISSUE THREAD

**Issue by pkarman** [PRX/fixer.prx.org#27]
app/processors/base_processor.rb, line 250, croaks when the URI has a *https* scheme. Seems like that should be aliased somehow into the http scheme, since Excon should support https just fine.

This affects downloading transcript text from PUA app.

**Comment by kookster** [comment]
This is my bad, I broke this when I refactored into modules for different schemes.

**Comment by kookster** [comment]
@pkarman the PR #28 fir this is ready to merge, if you want to give it a review first pls.
