### ISSUE TITLE
example of tasks with sequence

### ISSUE THREAD

**Issue by pkarman** [PRX/fixer.prx.org#33]
The tests have an example of creating a job with a sequence of tasks. That works ok directly at the model level.

However, I cannot seem to POST a job via the http interface with a sequence of tasks. The relevant controller seems to be `app/controllers/api/jobs_controller.rb` in the `job_params` method.

Can you include an example of creating a job with a task sequence, either here or (preferably) as an example on the fixer_client repo.

**Comment by kookster** [comment]
I think I see a problem with the controller not allowing enough params. I'll get on it.

- Andrew
